main

diff --git a/snowman-a/grade_utils b/snowman-a/grade_utils
--- a/snowman-a/grade_utils
+++ b/snowman-a/grade_utils
@@ -4,7 +4,7 @@
 set -o pipefail   # see https://unix.stackexchange.com/a/267031/16569
 exec 2>&1         # redirect stderr to stdout: https://unix.stackexchange.com/q/505581/16569
 
-TIMEOUT=10  # 10 seconds - default timeout
+TIMEOUT=1  # 1 second - default timeout
 
 typeset -F SECONDS
 SECONDS=0
@@ -24,46 +24,6 @@ run_in_folder_if_exists() {
 }
 
 
-# A function that echoes and executes a command.
-call() { 
-	echo "! ${@/eval/}" 
-	$@
-}
-
-# A function that echoes and executes a command.
-# If it fails, it sets grade=0.
-# If it succeeds, it sets grade=100.
-grade_command() { 
-	grade=100
-	call timeout $TIMEOUT $@
-	exitcode=$?
-	if [ $exitcode -ne 0 ]
-	then 
-		printf "*** Command failed. Exit code: $exitcode ***\n"
-		grade=0
-	fi
-	echo "--- $SECONDS seconds"
-}
-
-# A function that echoes and executes a command.
-# If it fails, it sets grade=0.
-# If it succeeds, it sets grade=[last line of output]
-grade_program() { 
-	program=$1
-	echo "! timeout $TIMEOUT ./$program" 
-	timeout $TIMEOUT ./$program
-	exitcode=$?
-	if [ $exitcode -ne 0 ]
-	then 
-		printf "*** Program failed. Exit code: $exitcode ***\n"
-		grade=0
-	else
-		grade=$( { timeout $TIMEOUT ./$program || echo 0; } | tail -n1 )
-	fi
-	echo "--- $SECONDS seconds"
-}
-
-
 
 # from here: https://stackoverflow.com/a/1115909/827927
 swap() {
@@ -78,4 +38,43 @@ swap() {
 	then
     	mv $2 $1
 	fi
+}
+
+# A function that echoes and executes a command.
+call() {
+	echo "! ${@/eval/}"
+	$@
+}
+
+# A function that echoes and executes a command.
+# If it fails, it sets grade=0.
+# If it succeeds, it sets grade=100.
+grade_command() {
+	grade=100
+	call timeout $TIMEOUT $@
+	exitcode=$?
+	if [ $exitcode -ne 0 ]
+	then
+		printf "*** Command failed. Exit code: $exitcode ***\n"
+		grade=0
+	fi
+	echo "--- $SECONDS seconds"
+}
+
+# A function that echoes and executes a command.
+# If it fails, it sets grade=0.
+# If it succeeds, it sets grade=[last line of output]
+grade_program() {
+	program=$1
+	echo "! timeout $TIMEOUT ./$program"
+	timeout $TIMEOUT ./$program
+	exitcode=$?
+	if [ $exitcode -ne 0 ]
+	then
+		printf "*** Program failed. Exit code: $exitcode ***\n"
+		grade=0
+	else
+		grade=$( { timeout $TIMEOUT ./$program || echo 0; } | tail -n1 )
+	fi
+	echo "--- $SECONDS seconds"
 }
